### PR TITLE
File Management and NEW TEI File for Vol. 1

### PR DESCRIPTION
**Pull request by RJP43**
Hey, Rob. Here is the file we worked on today from 4 - 5:30. Just merge the pull request with the green button and then the file will sit on your GitHub repo. Then once you click on the file you can view raw to download it or follow my [git tutorial](http://www.newtfire.org/dh/explainGitShell.html) to clone the repo to your local computer and pull in the document that way.

### CODE REVIEW

**Comment by ConnecticutDigital** [comment]
Ok I will

**Comment by ConnecticutDigital** [comment]
Just to let you know that I was unable to download github on my mac. Maybe
I should use my PC. Let me try it.

**Comment by RJP43** [comment]
@ConnecticutDigital We can have a look as of why when we meet next. Git is platform compatible so should be able to download on Mac. As long as we can share files it's less important you get on Git right now and more important that you are able to view the files "raw" and download them from [my forked versions of this repo](https://github.com/RJP43/Thomas-Bartram-Digital-Archives) 

On another note,  I was thinking about how we could code all those little symbols we are encountering and I think [this chapter of the TEI guidelines](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/WD.html) will be useful. With the `<g>` elements of particular interest and corresponding `@glyph` and `@charDecl` for the header. We can talk about all this more when we meet next. 

We might also consider giving transcribers a constrained web form like the [Letters of 1916 project](http://letters1916.maynoothuniversity.ie/diyhistory/scripto/transcribe/3543/9022) does with their crowdsourced transcriptions.

**Comment by RJP43** [comment]
@ConnecticutDigital I have organized the folders of this workspace and added our new TEI file for Vol. 1

**Comment by RJP43** [comment]
@ConnecticutDigital when we meet later today I can show you how to pull these changes into the main repository.

**Comment by ConnecticutDigital** [comment]
Ok great thanks!

**Pull request merged**
